---
- hosts: apptest
  become: yes

  tasks:
    # - name: Ensure Docker is installed
    #   package:
    #     name: docker
    #     state: present
      
    - name: Create destination directory
      file:
        path: /var/lib/deployed_app
        state: directory
        mode: '0755'


    - name: Copy application files to remote
      synchronize:
        src: /var/lib/jenkins/workspace/logg-app/logging-app
        dest: /var/lib/deployed_app/

    - name: Copy python application
      synchronize:
        src: /var/lib/jenkins/workspace/logg-app/python_app
        dest: /var/lib/deployed_app/logging-app/
 

    - name: Copy .env file from jenkins
      copy:
        src: /var/lib/jenkins/env/.env
        dest: /var/lib/deployed_app/logging-app/

    # - name: Copy .env file from jenkins
    #   copy:
    #     src: /var/lib/jenkins/env/.env_client
    #     dest: /var/lib/deployed_app/logging-app/client/.env

    # - name: Move python app into logging app
    #   shell: mv /var/lib/deployed_app/python_app /var/lib/deployed_app/logging-app/
    #   ignore_errors: yes

    - name: Deploy application using Docker Compose
      shell: docker-compose -f docker-compose.yml up --build -d
      args:
        chdir: /var/lib/deployed_app/logging-app/


