version: '3.8'

services:
  frontend:
    build:
      context: ./client/
      dockerfile: Dockerfile.React
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - app-data:/var/lib/client
    networks:
      - app-network
    restart: on-failure
    logging:
      driver: json-file
      options: 
        max-size: "100m"
        max-file: "10"
    
  node-app:
    build: 
      context: ./
      dockerfile: Dockerfile.Node
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - node-data:/var/lib/backend
    networks:
      - app-network
    depends_on:
      - frontend
    restart: on-failure
    logging:
      driver: json-file
      options: 
        max-size: "100m"
        max-file: "10"
    
  python_app:
    build:
      context: ./python_app/
      dockerfile: Dockerfile.Python
    ports:
      - "8080:80"
    volumes:
      - python_data:/var/lib/python-app # Inside container
    restart: on-failure


volumes:
  app-data:
  node-data:
  python_data:

networks:
  app-network:

